[default]
address = "127.0.0.1"
port = 8080
limits = { form = "64 kB", json = "1 MiB" }


#[global.tls]
#key = "keys/pokesize.key"     # Path or bytes to DER-encoded ASN.1 PKCS#1/#8 or SEC1 key.
#certs = "keys/pokesize.pem" # Path or bytes to DER-encoded X.509 TLS cert chain.
